apiVersion: v2
name: metaflow
description: Helm Chart to make deploying Metaflow on kubernetes as easy as possible.
type: application
version: 0.0.1
appVersion: "0.0.1"
maintainers:
- name: Zach Bloss
  email: zacharybloss@gmail.com
dependencies:
  - name: kubegres
    # repository: "charts/kubegres/"
    version: 0.0.1
    # import-values:
    #   - child: metaflow.labels
    #     parent: metaflow.labels