apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: {{ .Release.Name }}-kubegres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metaflow.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.db.replicas }}
  image: {{ .Values.db.image | default "" }}
  port: {{ .Values.db.port | default 5432 }}

  {{ if .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- range $v := .Values.imagePullSecrets }}
    - name: {{ $v.name }}
    {{- end }}
  {{- end }}

  {{ with .Values.db }}
  database:
    size: {{ .size }}
    {{ if .storageClassName }}storageClassName: {{ .storageClassName }}{{- end }}
    {{ if .volumeMount }}volumeMount: {{ .volumeMount }}{{- end }}

  {{ if .customConfigMap }}customConfig: {{ .customConfigMap }}{{- end }}

  failover:
    isDisabled: {{ not .failoverEnabled }}
    {{ if .promotePodToPrimary }}promotePod: {{ .promotePodToPrimary }}{{- end}}
  {{- end }}

  {{ with .Values.db.backup }}
  {{- if .enabled }}
  backup:
    schedule: {{ .schedule }}
    pvcName: {{ if .backupPvcName }}{{ .backupPvcName }}{{ else }}{{ $.Release.Name }}-kubegres-backup-pvc{{- end }}
    volumeMount: {{ .backupVolumeMount }}
  {{- end }}
  {{- end }}

  env:
  {{- with .Values.db }}
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ if .secrets.customSuperUserSecretName }}{{ .secrets.customSuperUserSecretName }}{{ else }}{{ $.Release.Name }}-secret{{- end }}
          key: {{ if .secrets.customSuperUserSecretValue }}{{ .secrets.customSuperUserSecretValue }}{{ else }}superUserPassword{{- end }}
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ if .secrets.customReplicaUserSecretName }}{{ .secrets.customReplicaUserSecretName }}{{ else }}{{ $.Release.Name }}-secret{{- end }}
          key: {{ if .secrets.customReplicaUserSecretValue }}{{ .secrets.customReplicaUserSecretValue }}{{ else }}replicaUserPassword{{- end }}

  {{- if .environmentVariables }}
  {{- range $v := .environmentVariables }}
    - name: {{ $v.name }}
      value: {{ $v.value | quote }}
  {{- end }}
  {{- end -}}
  {{- end }}
