apiVersion: v1
kind: Service
metadata:
  name: {{ include "metaflow-service.name" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metaflow.labels" . | nindent 4 }}
  annotations:
    {{- include "metaflow.annotations" . | nindent 4 }}
spec:
  selector:
    {{- include "metaflow-service.selectorLabels" . | nindent 4 }}
  type: {{ .Values.metaflowService.service.type }}
  ports:
    - name: metadata
      port: {{ .Values.metaflowService.service.port }}
      protocol: TCP
      targetPort: 8080
    - name: upgrades
      port: 8082
      protocol: TCP
      targetPort: 8082